# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Adapted from OpenRLHF (https://github.com/OpenRLHF/OpenRLHF),
# Copyright (c) OpenRLHF contributors, licensed under the Apache License, Version 2.0.

import os
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import numpy as np
import ray
import torch
from tqdm import tqdm
from vllm import SamplingParams

from molt.agents.base import _first_scalar as _to_scalar  # dedupe: same tensor/list/scalar normalizer
from molt.trainer.algorithm.experience import Experience
from molt.utils.logging_utils import init_logger
from molt.utils.vlm_utils import make_mm_train_input_spec

logger = init_logger(__name__)


@dataclass
class EvalExperience:
    """Scalar-only eval record that cannot pin rollout tensors in Ray plasma."""

    prompts: list = field(default_factory=list)
    group_ids: list = field(default_factory=list)
    rollout_ids: list = field(default_factory=list)
    rewards: list = field(default_factory=list)
    response_length: list = field(default_factory=list)
    truncated: list = field(default_factory=list)
    info: dict = field(default_factory=dict)


def _eval_scalar(value):
    """Detach one numeric value from tensor/list storage for eval aggregation."""
    value = _to_scalar(value)
    if isinstance(value, np.generic):
        value = value.item()
    if isinstance(value, (bool, int, float)):
        return value
    return None


def _compact_eval_experience(sample) -> EvalExperience:
    """Keep only fields consumed by ``compute_eval_metrics``.

    Multi-turn Experiences retain token, logprob, mask, and VLM tensors. Keeping
    an entire eval set therefore pins hundreds of GiB of zero-copy Ray objects.
    Converting the terminal statistics to Python scalars lets the source object
    be released as soon as each rollout is collected; training Experiences are
    intentionally untouched.
    """

    def first_item(name):
        values = getattr(sample, name, None) or []
        return [values[0]] if values else []

    def scalar_list(name):
        value = _eval_scalar(getattr(sample, name, None))
        return [] if value is None else [value]

    compact_info = {}
    for name, value in (getattr(sample, "info", None) or {}).items():
        scalar = _eval_scalar(value)
        if scalar is not None:
            compact_info[name] = scalar

    return EvalExperience(
        prompts=first_item("prompts"),
        group_ids=first_item("group_ids"),
        rollout_ids=first_item("rollout_ids"),
        rewards=scalar_list("rewards"),
        response_length=scalar_list("response_length"),
        truncated=scalar_list("truncated"),
        info=compact_info,
    )


def _collect_prompt_batch(dataloader_iter, num_prompts: int):
    """Draw up to `num_prompts` items from the prompt dataloader.

    Returns an exhaustion flag indicating whether the iterator is drained *after*
    collecting the returned prompts. Callers should still process any partial
    batch that was collected before exhaustion.
    """
    prompts, labels, images, tools = [], [], [], []
    exhausted = False

    while len(prompts) < num_prompts:
        try:
            _, batch_prompts, batch_labels, batch_images, batch_tools = next(dataloader_iter)
            remaining = num_prompts - len(prompts)
            prompts.extend(batch_prompts[:remaining])
            labels.extend(batch_labels[:remaining])
            images.extend(batch_images[:remaining])
            tools.extend(batch_tools[:remaining])
        except StopIteration:
            exhausted = True
            break

    return prompts, labels, images, tools, exhausted


def _build_action_token_mask(
    num_tokens: int, action_ranges: List[Tuple[int, int]], off_policy_lens: Optional[List[int]] = None
) -> torch.BoolTensor:
    """Mask token positions generated by the policy in a full multi-turn trajectory.

    ``off_policy_lens`` (one per action range, optional): the count of LEADING
    action tokens that were generated under stale pre-broadcast weights during a
    partial rollout. Those positions are left False, so they get zero policy
    gradient AND drop out of the global token-mean denominator — slime's
    mask_offpolicy_in_partial_rollout, but folded into the action mask so the loss
    path is unchanged. It is also used for the streaming slow tail when a refit
    spans requests that outlive their originating generation call.
    """
    mask = torch.zeros(num_tokens, dtype=torch.bool)
    for i, (start, end) in enumerate(action_ranges):
        if start < 0 or end < start or end > num_tokens:
            raise ValueError(f"Invalid action range ({start}, {end}) for trajectory length {num_tokens}")
        off = min(off_policy_lens[i], end - start) if off_policy_lens else 0
        mask[start + off : end] = True
    return mask


def _sample_group_key(sample) -> int | str:
    """Stable prompt-group key when rollout samples carry grouping metadata."""
    sample_group_ids = getattr(sample, "group_ids", None)
    return sample_group_ids[0] if sample_group_ids else id(sample)


class SamplesGenerator:
    """Stream prompts through a persistent pool of rollout workers."""

    def __init__(
        self,
        strategy,
        prompts_dataloader,
        eval_dataloader,
        tokenizer,
        agent_runners,
    ):
        self.strategy = strategy
        self.args = strategy.args

        self.tokenizer = tokenizer
        # Runner actors driving rollouts through the vllm-router; prompts are round-robined
        # across them (self._rr) — no pool wrapper, just a list + an index.
        self.agent_runners = agent_runners
        self._rr = 0

        self.prompts_dataloader = prompts_dataloader
        self.eval_dataloader = eval_dataloader

    # Warm-resume (opt-in via --ckpt.warm_resume_rollouts). At every train step, save the rollout
    # groups that finished but were NOT trained yet — the surplus kept beyond the batch just shipped
    # (self._finished_samples) — so a resumed run trains them right away instead of idling ~one
    # generation while the pipeline refills. Each step writes a FRESH file (never overwritten), so a
    # resume restores exactly its own checkpoint's untrained groups. Only the file PATH is returned;
    # the groups themselves are large and must not travel the Ray queue. Best-effort: on any failure
    # the run just resumes normally (regenerating those groups).
    _BUFFER = "rollout_buffer.pt"

    def state_dict(self) -> Dict:
        """Save this step's untrained rollout groups to a fresh sidecar file, return its path."""
        finished = getattr(self, "_finished_samples", None)
        if not getattr(self.args.ckpt, "warm_resume_rollouts", False) or not finished:
            return {}
        try:
            d = os.path.join(os.path.dirname(self.args.ckpt.path.rstrip("/")), "rollout_warm")
            os.makedirs(d, exist_ok=True)
            self._warm_seq = getattr(self, "_warm_seq", 0) + 1
            path = os.path.join(d, f"{self._BUFFER}.{os.getpid()}.{self._warm_seq}")  # pid+seq: unique per step
            torch.save(list(finished), path)
            for stale in sorted(os.scandir(d), key=lambda e: e.stat().st_mtime)[:-3]:  # keep newest 3; bound disk
                os.remove(stale.path)
            return {"buffer_file": path}
        except Exception as e:  # bookkeeping must never break the checkpoint
            logger.warning(f"warm-resume: save skipped ({e})")
            return {}

    def load_state_dict(self, state_dict: Optional[Dict]) -> None:
        """Restore this checkpoint's untrained groups (if any) to seed the first post-resume batch."""
        path = (state_dict or {}).get("buffer_file")
        if not path or not os.path.exists(path):
            return  # no file / failed save -> normal resume
        try:
            self._resumed_samples = torch.load(path, map_location="cpu", weights_only=False)
            logger.info(f"warm-resume: restored {len(self._resumed_samples)} rollout groups")
        except Exception as e:
            logger.warning(f"warm-resume: load skipped ({e})")

    @torch.no_grad()
    def generate_eval_samples(self, **generate_kwargs) -> List[EvalExperience]:
        """Generate the entire eval set into scalar-only records with a bounded pool."""
        if getattr(self, "_eval_dataloader_iter", None) is None:
            self._eval_dataloader_iter = iter(self.eval_dataloader)

        all_experiences: List[EvalExperience] = []
        eval_batch_size = getattr(self.args.eval, "batch_size", None) or self.args.rollout.batch_size
        if eval_batch_size <= 0:
            raise ValueError(f"eval.batch_size must be positive, got {eval_batch_size}")
        pending_refs: List = []
        exhausted = False
        drop_counts: Dict[str, int] = defaultdict(int)
        progress = tqdm(desc="Generate eval samples")
        try:
            while not exhausted or pending_refs:
                free_slots = eval_batch_size - len(pending_refs)
                if free_slots > 0 and not exhausted:
                    prompts, labels, images, tools, exhausted = _collect_prompt_batch(
                        self._eval_dataloader_iter, free_slots
                    )
                    if prompts:
                        pending_refs.extend(
                            self._dispatch_to_agent_runners(
                                prompts, labels, images=images, tools=tools, **generate_kwargs
                            )
                        )

                if not pending_refs:
                    break

                # Do not prefetch every pending result into this actor's object
                # store. Fetch exactly the one completed rollout selected below,
                # compact it to scalars, then release its large Ray tensors.
                ready_refs, pending_refs = ray.wait(
                    pending_refs, num_returns=1, timeout=10.0, fetch_local=False
                )
                for ref in ready_refs:
                    all_experiences.extend(
                        _compact_eval_experience(sample)
                        for sample in self._filter_group(ref, False, drop_counts, **generate_kwargs)
                    )
                    progress.update(1)
        finally:
            progress.close()
            self._eval_dataloader_iter = None

        if drop_counts:
            logger.info(f"Eval rollout drops: {dict(drop_counts)}")

        return all_experiences

    @torch.no_grad()
    def generate_samples(self, **generate_kwargs) -> Tuple[List[Experience], Dict[str, float], int, bool]:
        """Stream one training-sized batch out of a continuously-refilled rollout pool.

        Normally keeps `vllm_generate_batch_size` prompt rollouts in flight and
        returns as soon as `rollout.batch_size` prompt groups have finished; the
        slow tail persists across calls for asynchronous overlap. Strict
        force-on-policy mode instead dispatches at most the groups still needed,
        so the batch boundary drains with no old-policy tail.

        Multi-turn agents emit several step-samples per rollout, so we chunk by
        GROUP (= prompt): each returned batch holds `rollout.batch_size` prompts,
        each with its N rollouts × K_i step-samples. Safe with `partial_rollout` —
        a weight refit pauses/resumes the engines (see broadcast_to_vllm), so the
        in-flight rollouts survive it.
        """
        # Iterator exhaustion can happen while a slow tail is still in flight.
        # Keep an explicit episode lifecycle so the next call does not restart
        # the dataset before that tail drains.
        if not getattr(self, "_episode_active", False):
            self._dataloader_iter = iter(self.prompts_dataloader)
            # Seed from a warm-resume buffer if load_state_dict restored one, so the first
            # post-resume batch ships without waiting for a full fresh generation. Consumed once.
            self._finished_samples: List[Experience] = list(getattr(self, "_resumed_samples", None) or [])
            self._resumed_samples = None
            self._inflight_rollouts: List = []
            self._episode_active = True

        groups_per_batch = self.args.rollout.batch_size
        inflight_capacity = getattr(self.args.rollout, "vllm_generate_batch_size", None) or groups_per_batch
        dynamic_filtering = self.args.algo.dynamic_filtering_enable
        force_on_policy = bool(getattr(getattr(self.args, "train", None), "force_on_policy", False))

        def finished_group_count() -> int:
            return len({_sample_group_key(sample) for sample in self._finished_samples})

        prompts_dispatched = 0
        groups_accepted = 0
        drop_counts: Dict[str, int] = defaultdict(int)
        score_stats: Dict[str, float] = defaultdict(float)  # pre-DAPO-filter score stats
        progress = tqdm(
            total=groups_per_batch, initial=min(finished_group_count(), groups_per_batch), desc="Generate samples"
        )

        while finished_group_count() < groups_per_batch:
            # Async mode saturates the pool continuously. Strict on-policy mode
            # never dispatches a group beyond this batch: any slow tail crossing
            # the subsequent refit would make the next update off-policy.
            free_slots = inflight_capacity - len(self._inflight_rollouts)
            if force_on_policy:
                groups_needed = groups_per_batch - finished_group_count() - len(self._inflight_rollouts)
                free_slots = min(free_slots, groups_needed)
            if free_slots > 0 and self._dataloader_iter is not None:
                prompts, labels, images, tools, dataloader_exhausted = _collect_prompt_batch(
                    self._dataloader_iter, free_slots
                )
                prompts_dispatched += len(prompts)
                if prompts:
                    self._inflight_rollouts.extend(
                        self._dispatch_to_agent_runners(prompts, labels, images=images, tools=tools, **generate_kwargs)
                    )
                if dataloader_exhausted:
                    self._dataloader_iter = None
                    logger.info("Prompt dataloader is exhausted.")

            if not self._inflight_rollouts:
                break  # dataloader drained and pool empty — emit whatever finished

            # Take the first rollout to finish; the slow ones keep generating in vLLM.
            ready, self._inflight_rollouts = ray.wait(self._inflight_rollouts, num_returns=1)
            for finished_rollout in ready:
                # Dropped groups (filtered or all-unusable) come back empty; their
                # slot is refilled with a fresh prompt on the next iteration.
                group_samples = self._filter_group(
                    finished_rollout, dynamic_filtering, drop_counts, score_stats=score_stats, **generate_kwargs
                )
                if group_samples:
                    self._finished_samples.extend(group_samples)
                    groups_accepted += 1
                    progress.update(1)
        progress.close()

        # Observability: per-reason drop counts + (when filtering) the pass rate.
        rollout_metrics = {f"rollout/dropped/{reason}": float(n) for reason, n in drop_counts.items()}
        if drop_counts:
            rollout_metrics["rollout/dropped/total"] = float(sum(drop_counts.values()))
        if dynamic_filtering and prompts_dispatched:
            rollout_metrics["dynamic_filtering_pass_rate"] = groups_accepted / prompts_dispatched * 100
        # Pre-filter stats: the model's TRUE judge pass rate over ALL scored samples, BEFORE DAPO
        # drops uniform groups. (post-filter `reward`/`pivotrl_correct` only covers kept MIXED groups
        # ~0.5-0.65 by construction, so it hides the real pass rate + the all-pass saturation.)
        if score_stats.get("score_n", 0) > 0:
            rollout_metrics["rollout/pre_filter_mean_score"] = score_stats["score_sum"] / score_stats["score_n"]
        if score_stats.get("groups", 0) > 0:
            rollout_metrics["rollout/group_all_pass_rate"] = score_stats["all_pass"] / score_stats["groups"] * 100
            rollout_metrics["rollout/group_all_fail_rate"] = score_stats["all_fail"] / score_stats["groups"] * 100

        # Hand back exactly `groups_per_batch` finished groups; keep any surplus for the next call.
        selected_groups: set = set()
        batch_samples: List[Experience] = []
        leftover_samples: List[Experience] = []
        for sample in self._finished_samples:
            group_key = _sample_group_key(sample)
            if group_key in selected_groups or len(selected_groups) < groups_per_batch:
                selected_groups.add(group_key)
                batch_samples.append(sample)
            else:
                leftover_samples.append(sample)
        self._finished_samples = leftover_samples
        if force_on_policy:
            if self._finished_samples:
                raise RuntimeError("force_on_policy left finished groups beyond the batch boundary")
            if self._inflight_rollouts:
                raise RuntimeError("force_on_policy left old-policy rollouts in flight")

        # Exhausted only once the dataloader is done AND nothing is buffered or in flight.
        exhausted = self._dataloader_iter is None and not self._finished_samples and not self._inflight_rollouts
        if exhausted:
            self._episode_active = False
        return batch_samples, rollout_metrics, prompts_dispatched, exhausted

    def _passes_dynamic_filter(self, group_samples) -> bool:
        """Whether a scored group's mean reward lands inside the dynamic-filtering range.

        A group with any unscored sample always passes — filtering only applies once
        every sample in the group has a score.
        """
        if not all(s.scores is not None for s in group_samples):
            return True
        scores = [s.scores[0].item() for s in group_samples]
        mean_score = sum(scores) / len(scores)
        min_score, max_score = self.args.algo.dynamic_filtering_range
        if min_score < mean_score < max_score:
            return True
        logger.info(
            f"Filtered out group: mean_score={mean_score:.2f}, range=({min_score:.2f}, {max_score:.2f}), "
            f"scores={[f'{s:.2f}' for s in scores]}"
        )
        return False

    def _filter_group(
        self,
        finished_rollout,
        dynamic_filtering: bool,
        drop_counts: Dict[str, int],
        score_stats: Dict[str, float] | None = None,
        **generate_kwargs,
    ) -> List[Experience]:
        """Filter one finished rollout (a prompt's N responses = one group) down to
        its kept Experiences, tallying every drop into ``drop_counts`` by reason.

        The single place the keep/drop policy lives, applying both filters:
        per-response (unusable trajectories, via ``_process_response_into_experience``)
        and the group-level DAPO dynamic-reward filter. Returns ``[]`` when the
        whole group is dropped. Both the streaming (``generate_samples``) and
        batch/eval (``_generate_batch``) paths call it, so the per-group filter loop
        is never reimplemented.
        """
        group_samples: List[Experience] = []
        force_on_policy = bool(getattr(getattr(self.args, "train", None), "force_on_policy", False))
        rollout_kind = str(generate_kwargs.get("rollout_kind", "train")).strip().lower()
        for response in ray.get(finished_rollout):
            experience, drop_reason = self._process_response_into_experience(response, **generate_kwargs)
            if experience is not None:
                group_samples.append(experience)
            elif drop_reason is not None:
                drop_counts[drop_reason] += 1
                if force_on_policy and rollout_kind == "train" and drop_reason == "backend_error":
                    raise RuntimeError(
                        "force_on_policy training rollout reported a backend error; "
                        "refusing to skip the affected prompt or train on a synthetic reward"
                    )

        # Training must keep complete sibling groups even when DAPO filtering is
        # disabled. Evaluation retains partial groups so infrastructure failures
        # remain visible to the strict audit instead of being silently hidden.
        require_complete_group = dynamic_filtering or rollout_kind == "train"
        if require_complete_group and group_samples:
            n_samples = generate_kwargs.get("n_samples_per_prompt", self.args.rollout.n_samples_per_prompt)
            n_rollouts = len({(s.rollout_ids[0] if getattr(s, "rollout_ids", None) else id(s)) for s in group_samples})
            if n_rollouts < n_samples:
                drop_counts["incomplete_group"] += len(group_samples)
                return []

        if dynamic_filtering and group_samples:
            # Pre-filter score stats (the model's TRUE judge pass rate over scored samples, BEFORE
            # DAPO drops uniform groups). Accumulate here, before any keep/drop decision, so the
            # logged mean reflects all-pass + all-fail + mixed (not just the kept mixed groups).
            if score_stats is not None:
                scored = [s.scores[0].item() for s in group_samples if s.scores is not None]
                if scored:
                    min_score, max_score = self.args.algo.dynamic_filtering_range
                    gmean = sum(scored) / len(scored)
                    score_stats["score_sum"] += sum(scored)
                    score_stats["score_n"] += len(scored)
                    score_stats["groups"] += 1.0
                    score_stats["all_pass"] += float(gmean >= max_score)
                    score_stats["all_fail"] += float(gmean <= min_score)
            if not self._passes_dynamic_filter(group_samples):
                drop_counts["dynamic_filter"] += len(group_samples)
                return []
        return group_samples

    def _generate_batch(
        self, dataloader_iter, num_prompts: int, dynamic_filtering, **generate_kwargs
    ) -> Tuple[List[Experience], int, bool]:
        """Generate a batch of Experiences with optional reward filtering.

        Dispatches num_prompts across the runner actors (which generate through the
        vllm-router), collects all results, and returns. When dynamic_filtering is
        enabled, filtered prompts are replaced with new ones.
        """
        prompts_consumed = 0
        accepted_experiences: List[Experience] = []
        drop_counts: Dict[str, int] = defaultdict(int)

        prompts, labels, images, tools, exhausted = _collect_prompt_batch(dataloader_iter, num_prompts)
        if not prompts:
            return [], prompts_consumed, True

        target_num_prompts = len(prompts)
        pending_refs = self._dispatch_to_agent_runners(prompts, labels, images=images, tools=tools, **generate_kwargs)
        prompts_consumed += target_num_prompts

        pbar = tqdm(range(target_num_prompts), desc="Generate samples")

        while pending_refs:
            ready_refs, pending_refs = ray.wait(pending_refs, num_returns=1, timeout=10.0)
            for ref in ready_refs:
                # One ref == one prompt's full rollout (n_samples responses) = one
                # prompt group. Same keep/drop policy as the streaming path, via the
                # shared _filter_group (dynamic filtering is per-group, like DAPO).
                group_experiences = self._filter_group(ref, dynamic_filtering, drop_counts, **generate_kwargs)

                if group_experiences:
                    accepted_experiences.extend(group_experiences)
                    pbar.set_postfix({"prompts_consumed": prompts_consumed})
                    pbar.update()
                elif dynamic_filtering and not exhausted:
                    # Dispatch a replacement for the filtered prompt, but only
                    # while the dataloader still has prompts. Never ray.cancel
                    # the remaining in-flight rollouts: draining them keeps the
                    # already-generated valid experiences (and an accurate
                    # prompts_consumed count) instead of discarding work at the
                    # dataloader boundary.
                    new_prompts, new_labels, new_images, new_tools, exhausted = _collect_prompt_batch(
                        dataloader_iter, 1
                    )
                    prompts_consumed += len(new_prompts)
                    if new_prompts:
                        new_refs = self._dispatch_to_agent_runners(
                            new_prompts, new_labels, images=new_images, tools=new_tools, **generate_kwargs
                        )
                        pending_refs.extend(new_refs)

        if drop_counts:
            logger.info(f"Eval rollout drops: {dict(drop_counts)}")
        return accepted_experiences, prompts_consumed, exhausted

    def _dispatch_to_agent_runners(
        self, prompts: List[str], labels: List[str], *, images: List = None, tools: List = None, **generate_kwargs
    ) -> List:
        """Round-robin each prompt group onto the runner actors; each ``run_group`` returns a
        Ray ref of that group's Trajectories, consumed by the streaming loop / filtering /
        experience maker exactly as before."""
        sampling_params = SamplingParams(
            temperature=generate_kwargs.get("temperature", 1.0),
            top_p=generate_kwargs.get("top_p", 1.0),
            top_k=generate_kwargs.get("top_k", -1),
            max_tokens=generate_kwargs.get("max_new_tokens"),  # None = dynamic per-prompt
            min_tokens=generate_kwargs.get("min_new_tokens", 1),
            skip_special_tokens=generate_kwargs.get("skip_special_tokens", False),
            logprobs=1 if self.args.algo.advantage.is_correction_level != "off" else None,
        )
        truncate_length = generate_kwargs.get("max_len", 2048)
        n_samples = generate_kwargs.get("n_samples_per_prompt", self.args.rollout.n_samples_per_prompt)
        rollout_kind = generate_kwargs.get("rollout_kind", "train")
        policy_version = int(generate_kwargs.get("policy_version", 0))
        policy_frozen = bool(generate_kwargs.get("policy_frozen", False))
        if images is None:
            images = [None] * len(prompts)
        if tools is None:
            tools = [None] * len(prompts)

        refs = []
        for prompt, label, img, tool in zip(prompts, labels, images, tools):
            actor = self.agent_runners[self._rr % len(self.agent_runners)]
            self._rr += 1
            refs.append(
                actor.run_group.remote(
                    prompt,
                    label,
                    img,
                    sampling_params,
                    truncate_length,
                    n_samples,
                    tools=tool,
                    rollout_kind=rollout_kind,
                    policy_version=policy_version,
                    policy_frozen=policy_frozen,
                    base_seed=int(self.args.train.seed),
                )
            )
        return refs

    def _media_token_ids(self) -> set:
        """Image/video placeholder token ids from the tokenizer/processor (cached)."""
        cache = getattr(self, "_media_ids_cache", None)
        if cache is not None:
            return cache
        ids: set = set()
        tok = self.tokenizer
        for obj in (tok, getattr(tok, "tokenizer", None)):
            if obj is None:
                continue
            for attr in ("image_token_id", "video_token_id", "img_context_token_id", "video_context_token_id"):
                tid = getattr(obj, attr, None)
                if isinstance(tid, int):
                    ids.add(tid)
        self._media_ids_cache = ids
        return ids

    def _process_response_into_experience(
        self, response, **generate_kwargs
    ) -> Tuple[Optional[Experience], Optional[str]]:
        """Turn one Trajectory (from agent Runner) into an Experience.

        Returns ``(experience, None)`` when the rollout is usable, or
        ``(None, drop_reason)`` when it must be dropped — the reason is a short
        code (e.g. ``"vlm_truncation"``, ``"no_action_tokens"``) that
        ``_filter_group`` tallies into the ``rollout/dropped/<reason>`` metrics.
        """
        truncate_length = generate_kwargs.get("max_len", 2048)
        step_slice = slice(1, truncate_length)

        # Infrastructure failures are not negative policy outcomes. Keep them
        # in evaluation so the audit can fail visibly, but never train on their
        # synthetic zero reward or corrupt a sibling baseline.
        rollout_kind = str(generate_kwargs.get("rollout_kind", "train")).strip().lower()
        if rollout_kind == "train":
            extra_logs = response.extra_logs or {}
            backend_error = any(
                bool(_to_scalar(extra_logs.get(key))) for key in ("nanobot_backend_error", "esibench_backend_error")
            )
            if backend_error:
                logger.warning("Skipping training rollout terminated by a backend error.")
                return None, "backend_error"

        trajectory_tokens = response.observation_tokens.copy()
        if not trajectory_tokens:
            logger.warning("Skipping rollout response with empty observation_tokens.")
            return None, "empty_tokens"

        # VLM safety: the truncation below cuts the token sequence at
        # `truncate_length` but mm_train_inputs (pixel_values / image_grid_thw)
        # stays full-size. If truncation removes any image/video placeholder
        # token, the actor's vit-embed scatter misaligns with the pixel_values
        # rows — a SILENT train/rollout policy mismatch (actor.forward only
        # warns once). Drop such rollouts instead of training on corrupt data.
        if response.mm_train_inputs is not None and len(trajectory_tokens) > truncate_length:
            media_ids = self._media_token_ids()
            dropped_media = (
                sum(1 for t in trajectory_tokens[truncate_length:] if t in media_ids) if media_ids else None
            )
            if dropped_media is None:
                logger.warning(
                    "Skipping VLM rollout: trajectory exceeds max_len and image token ids could not be "
                    "resolved to verify truncation safety. Increase --max_len / --max_new_tokens."
                )
                return None, "vlm_media_unresolved"
            if dropped_media:
                logger.warning(
                    f"Skipping VLM rollout: truncation at max_len={truncate_length} would drop {dropped_media} "
                    "image/video placeholder token(s) while pixel_values stays full-size (vit-embed "
                    "misalignment). Increase --max_len or --max_new_tokens."
                )
                return None, "vlm_truncation"

        reward_val = _to_scalar(response.reward)
        score_val = _to_scalar(response.scores)

        sequences = torch.tensor(trajectory_tokens, dtype=torch.long)
        attention_mask = torch.ones(len(trajectory_tokens), dtype=torch.long)
        action_token_mask = _build_action_token_mask(
            len(trajectory_tokens), response.action_ranges, response.off_policy_action_lens
        )

        # Truncate token-axis tensors to the configured context window.
        sequences = sequences[:truncate_length].to("cpu")
        attention_mask = attention_mask[:truncate_length].to("cpu")

        # Step-axis tensors align with next-token logprobs: token position k is
        # predicted from position k-1, so we drop token position 0. Multi-turn
        # environment/tool feedback stays on this dense axis with mask=False.
        action_mask = action_token_mask[step_slice].to("cpu")
        raw_rollout_log_probs = response.rollout_log_probs
        if raw_rollout_log_probs is not None:
            if len(raw_rollout_log_probs) != len(trajectory_tokens):
                logger.warning(
                    "rollout_log_probs must align with observation_tokens before the next-token shift: "
                    f"got {len(raw_rollout_log_probs)} logprobs for {len(trajectory_tokens)} tokens; "
                    "skipping rollout response."
                )
                return None, "logprob_misalign"
            rollout_log_probs = torch.tensor(raw_rollout_log_probs[step_slice]).to("cpu")
        else:
            rollout_log_probs = None

        # Number of generated action tokens (multi-turn observation gaps don't count).
        response_length = int(action_mask.sum().item())
        if response_length == 0:
            logger.warning("Skipping rollout response with no trainable action tokens.")
            return None, "no_action_tokens"
        total_length = attention_mask.float().sum()
        is_clipped = total_length >= truncate_length

        info = {"response_clip_ratio": torch.tensor([is_clipped])}
        if response.mm_train_inputs is not None and (media_ids := self._media_token_ids()):
            # Embedded image tokens that actually enter training. An image silently dropped
            # or rendered at reduced resolution shrinks this count while reward/vllm_kl stay
            # plausible — the one visible trace of an image-blind rollout.
            info["image_tokens"] = torch.tensor(
                [sum(1 for t in trajectory_tokens[:truncate_length] if t in media_ids)]
            )
        if reward_val is not None:
            info["reward"] = torch.tensor([reward_val])
        if score_val is not None:
            info["score"] = torch.tensor([score_val])

        # Convert extra logs to tensors for downstream consumers. Skip
        # non-numeric values (e.g. string task ids) —
        # `torch.tensor([str])` raises "too many dimensions 'str'".
        for key, value in (response.extra_logs or {}).items():
            value = _to_scalar(value)
            if isinstance(value, (int, float, bool)):
                info[key] = torch.tensor([value])
        if "generation_truncated" in info:
            # Post-tokenization clipping is another generation/context cutoff.
            # Fold it into the explicit signal without conflating a terminal
            # environment horizon carried by response.truncated.
            info["generation_truncated"] = torch.tensor(
                [bool(_to_scalar(info["generation_truncated"])) or bool(is_clipped)]
            )

        # R3: per-token rollout routing aligned with `sequences` (one [L, K] expert-id
        # row per token), seq last after the permute below.
        routed_experts = None
        if response.routed_experts is not None:
            row_shape = next((r.shape for r in response.routed_experts if r is not None), None)
            if row_shape is not None:
                # Positions with no captured rollout routing (a multimodal prompt the engine
                # didn't route, feedback, the trailing token) get a -1 sentinel: the training
                # forward keeps its own natural routing there (RouterReplay). Zeros would
                # instead force those tokens to expert 0 and corrupt the forward.
                sentinel = np.full(row_shape, -1, dtype=np.int16)
                rows = [r if r is not None else sentinel for r in response.routed_experts]
                # int16, not the engine's uint8: the training side pads the CP tail with the -1
                # sentinel, which on uint8 wraps to 255 and (for models with <256 experts, e.g.
                # omni3's 128) indexes out of bounds -> device-side assert in the router gather.
                arr = np.stack(rows).astype(np.int16)[:truncate_length]  # (T, L, K), aligned with sequences
                routed_experts = torch.from_numpy(arr).permute(1, 2, 0).contiguous().unsqueeze(0)  # (1, L, K, T)

        compact_mm_transport = (
            os.environ.get("MOLT_COMPACT_VLM_EXPERIENCE", "0") == "1"
            and response.mm_train_inputs is not None
            and bool(response.pil_images)
        )
        if compact_mm_transport and not hasattr(self.tokenizer, "image_processor"):
            raise RuntimeError("MOLT_COMPACT_VLM_EXPERIENCE=1 requires a processor.image_processor")
        mm_train_input_specs = (
            [make_mm_train_input_spec(response.mm_train_inputs)] if compact_mm_transport else []
        )

        experience = Experience(
            sequences=sequences.unsqueeze(0),
            attention_mask=attention_mask.unsqueeze(0),
            action_mask=action_mask.unsqueeze(0),
            rollout_log_probs=rollout_log_probs.unsqueeze(0) if rollout_log_probs is not None else None,
            routed_experts=routed_experts,
            prompts=[response.prompt],
            labels=[response.label],
            # Compact mode carries the lossless PIL observations instead of
            # enormous float32 patch tensors across the generator->trainer Ray
            # queue. The trainer reconstructs and fingerprints the exact
            # processor outputs before any forward. Default mode preserves the
            # existing preprocessed payload and drops the unused raw copy.
            images=[list(response.pil_images)] if compact_mm_transport else [],
            mm_train_inputs=[] if compact_mm_transport else [response.mm_train_inputs],
            mm_train_input_specs=mm_train_input_specs,
            group_ids=[response.group_id] if response.group_id is not None else [],
            rollout_ids=[response.rollout_id] if response.rollout_id is not None else [],
            rewards=torch.tensor([reward_val]) if reward_val is not None else None,
            scores=torch.tensor([score_val]) if score_val is not None else None,
            response_length=torch.tensor([response_length]),
            truncated=torch.tensor([bool(response.truncated) or bool(is_clipped)]),
            total_length=torch.tensor([total_length]),
            info=info,
        )
        return experience, None
