# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import asyncio
from types import SimpleNamespace

import numpy as np
import pytest
import torch

import molt.agents._chat_server as cs
from molt.agents._chat_server import (
    ChatServerState,
    _anthropic_message_body,
    _chat_completion_body,
    _content_to_text_and_images,
    _decode_anthropic,
    _run_turn,
    stitch_session,
)
from molt.agents.base import Result


# ---------------------------------------------------------------------------
# Fakes: the transport exposes generate(token_ids, sp, multi_modal_data) over the
# router's /v1/completions (same call the step runner uses). Client-side templating
# (apply_chat_template + _tokenize_observation) is monkeypatched so tests drive the
# exact prompt token ids per turn.
# ---------------------------------------------------------------------------
class _FakeTransport:
    def __init__(self, actions):  # actions: list of (action_ids, logprobs, finish, routed)
        self.actions = list(actions)
        self.calls = []

    async def generate(self, prompt_token_ids, sampling_params, multi_modal_data=None, session_id=None):
        self.calls.append((list(prompt_token_ids), multi_modal_data, sampling_params.max_tokens))
        aids, lps, finish, routed = self.actions.pop(0)
        logprobs = [{t: SimpleNamespace(logprob=lp)} for t, lp in zip(aids, lps)]
        gen = SimpleNamespace(
            token_ids=list(aids),
            text="ACT",
            finish_reason=finish,
            logprobs=logprobs,
            routed_experts=np.asarray(routed) if routed is not None else None,
        )
        return SimpleNamespace(outputs=[gen], prompt_routed_experts=None), 0


def _proc():
    # apply_chat_template output is fed to the monkeypatched _tokenize_observation, so its value is
    # irrelevant; image_token == "<image>" -> should_expand is False (no structured-content split).
    return SimpleNamespace(apply_chat_template=lambda chat, **k: "TEXT", image_token="<image>")


def _sampling(max_tokens=8):
    return SimpleNamespace(max_tokens=max_tokens, temperature=1.0, top_p=1.0, logprobs=1, min_tokens=0)


def _state(actions, *, max_length=1000):
    st = ChatServerState(_FakeTransport(actions), _proc(), "policy", max_length, _sampling())
    return st, st.transport


def _act(action_ids, logprobs, *, finish="stop", routed=None):
    return (action_ids, logprobs, finish, routed)


def _patch_prompts(monkeypatch, prompts, *, mm=None, pil=None):
    """Drive the per-turn prompt token ids (what apply_chat_template + processor would produce)."""
    q = list(prompts)
    monkeypatch.setattr(cs, "_tokenize_observation", lambda proc, text, imgs: (q.pop(0), mm, pil or []))


_MSG = {"messages": [{"role": "user", "content": "P"}]}


# ---------------------------------------------------------------------------
# Multi-turn fakes: a char-level template + tokenizer that deliberately does NOT round-trip
# generated bytes — it TRIMS a trailing </think> when rendering an assistant turn (like qwen3.6)
# and wraps assistants in tags. A naive full re-render of turn N would therefore drift from the
# exact generated tokens; the TITO delta path must not. The engine decodes action text from the
# ids (like the token-only router) and can tag its prefill/gen routing per turn.
# ---------------------------------------------------------------------------
class _DriftyProc:
    image_token = "<image>"  # literal placeholder -> no structured-content split

    def apply_chat_template(self, chat, tokenize=False, add_generation_prompt=False, **kwargs):
        out = ""
        for m in chat:
            content = m["content"]
            if m["role"] == "assistant" and content.endswith("</think>"):
                content = content[: -len("</think>")]  # non-round-trip trim
            out += f"<{m['role']}>{content}</{m['role']}>"
        return out + ("<gen>" if add_generation_prompt else "")

    def __call__(self, text=None, add_special_tokens=False, return_tensors=None):
        return {"input_ids": torch.tensor([[ord(c) for c in text]])}

    def decode(self, ids, skip_special_tokens=False):
        return "".join(chr(i) for i in ids)


class _DriftyEngine:
    def __init__(self, actions):  # actions: (action_ids, logprobs, finish, tag)
        self.actions = list(actions)
        self.prompts = []

    async def generate(self, prompt_token_ids, sp, multi_modal_data=None, session_id=None):
        self.prompts.append(list(prompt_token_ids))
        aids, lps, finish, tag = self.actions.pop(0)
        logprobs = [{t: SimpleNamespace(logprob=lp)} for t, lp in zip(aids, lps)]
        # tag!=None: routing per turn. gen omits the LAST action token (a trailing sampled token has
        # no routing at gen time); the prefill (prompt routing) covers the whole prefix, so the next
        # turn backfills that boundary position first-writer-wins.
        gen_re = np.asarray([[[tag]]] * (len(aids) - 1), dtype=np.int16) if tag is not None else None
        prompt_re = np.asarray([[[tag]]] * len(prompt_token_ids), dtype=np.int16) if tag is not None else None
        gen = SimpleNamespace(
            token_ids=list(aids), text="", finish_reason=finish, logprobs=logprobs, routed_experts=gen_re
        )
        return SimpleNamespace(outputs=[gen], prompt_routed_experts=prompt_re), 0


def _dact(action_ids, logprobs, *, finish="stop", tag=None):
    return (action_ids, logprobs, finish, tag)


def _ids(s):
    return [ord(c) for c in s]


def _drive(state, session, messages):
    return asyncio.run(_run_turn(state, session, {"messages": messages}))


# ---------------------------------------------------------------------------
# Forward: tokenize (client-side) -> generate (token-in over /v1/completions) ->
# one token-exact Trajectory step-sample.
# ---------------------------------------------------------------------------
def test_run_turn_records_exact_tokens(monkeypatch):
    _patch_prompts(monkeypatch, [[1, 2, 3]])
    state, tp = _state([_act([90, 91], [-0.3, -0.4])])
    state.open("sid", "P", "lab", None)
    session = state.sessions["sid"]

    action, finish = asyncio.run(_run_turn(state, session, _MSG))

    assert (action, finish) == ("ACT", "stop")
    assert tp.calls[0][0] == [1, 2, 3]  # generate fed the tokenized prompt
    traj = session.trajectories[0]
    assert traj.observation_tokens == [1, 2, 3, 90, 91]
    assert traj.action_ranges == [(3, 5)]
    assert traj.rollout_log_probs == [0.0, 0.0, 0.0, -0.3, -0.4]
    assert traj.prompt == "P" and traj.label == "lab"


def test_multiturn_trajectory_is_token_exact_and_unfragmented():
    # Drive 3 real turns through the drifty (non-round-tripping) template. The accumulated trajectory
    # must be EXACTLY turn1_prompt + action1 + delta2 + action2 + delta3 + action3, each action's
    # tokens byte-identical to what the engine generated — one unfragmented, drift-free trajectory.
    a1, a2, a3 = "A1</think>", "A2</think>", "A3"
    engine = _DriftyEngine(
        [_dact(_ids(a1), [-0.1] * len(a1)), _dact(_ids(a2), [-0.2] * len(a2)), _dact(_ids(a3), [-0.3] * len(a3))]
    )
    state = ChatServerState(engine, _DriftyProc(), "policy", 10000, _sampling())
    state.open("sid", "P", "lab", None)
    session = state.sessions["sid"]

    msgs = [{"role": "user", "content": "Q0"}]
    act1, _ = _drive(state, session, msgs)
    # Stateless chat: append the model's reply + a tool observation, resend the whole history.
    msgs = msgs + [{"role": "assistant", "content": act1}, {"role": "user", "content": "OBS1"}]
    act2, _ = _drive(state, session, msgs)
    msgs = msgs + [{"role": "assistant", "content": act2}, {"role": "user", "content": "OBS2"}]
    act3, _ = _drive(state, session, msgs)
    assert (act1, act2, act3) == (a1, a2, a3)  # decoded actions keep </think> (no template trim)

    proc = _DriftyProc()

    def render(chat, gen):
        return proc.apply_chat_template(chat, add_generation_prompt=gen)

    turn1_prompt = _ids(render([{"role": "user", "content": "Q0"}], True))
    delta2 = _ids(render([{"role": "user", "content": "OBS1"}], True))  # suffix after the shared prefix
    delta3 = _ids(render([{"role": "user", "content": "OBS2"}], True))
    expected = turn1_prompt + _ids(a1) + delta2 + _ids(a2) + delta3 + _ids(a3)

    traj = session.trajectories[0]
    assert traj.observation_tokens == expected  # token-exact, single growing trajectory
    assert engine.prompts[1] == turn1_prompt + _ids(a1) + delta2  # turn 2 generated over the exact tokens
    assert [traj.observation_tokens[s:e] for s, e in traj.action_ranges] == [_ids(a1), _ids(a2), _ids(a3)]
    assert traj.rollout_log_probs == (
        [0.0] * len(turn1_prompt)
        + [-0.1] * len(a1)
        + [0.0] * len(delta2)
        + [-0.2] * len(a2)
        + [0.0] * len(delta3)
        + [-0.3] * len(a3)
    )
    # Proof the fix matters: a naive full re-render of the history does NOT reproduce turn-1's exact
    # tokens (the template trims </think> + wraps the assistant), so the old prefix-merge would split.
    turn1_exact = turn1_prompt + _ids(a1)
    naive = _ids(render(msgs, True))
    assert naive[: len(turn1_exact)] != turn1_exact


def test_multiturn_routing_backfills_turn_boundary():
    # R3 routing is laid down per turn (absorb_routing, first-writer-wins). Assert it stays aligned
    # 1:1 with tokens and that a prior action's trailing token — unrouted at gen time — is backfilled
    # by the next turn's prefill, exactly like the old merge did explicitly.
    engine = _DriftyEngine([_dact(_ids("X1"), [-0.1, -0.1], tag=11), _dact(_ids("Y2"), [-0.2, -0.2], tag=22)])
    state = ChatServerState(engine, _DriftyProc(), "policy", 10000, _sampling())
    state.open("sid", "P", "l", None)
    session = state.sessions["sid"]
    msgs = [{"role": "user", "content": "Q0"}]
    act1, _ = _drive(state, session, msgs)
    msgs = msgs + [{"role": "assistant", "content": act1}, {"role": "user", "content": "OBS1"}]
    _drive(state, session, msgs)

    proc = _DriftyProc()
    p1 = len(_ids(proc.apply_chat_template([{"role": "user", "content": "Q0"}], add_generation_prompt=True)))
    traj = session.trajectories[0]
    re = traj.routed_experts

    def val(i):
        return None if re[i] is None else int(re[i][0][0])

    assert len(re) == len(traj.observation_tokens)  # aligned 1:1 with tokens
    assert all(val(i) == 11 for i in range(p1))  # shared prefix keeps turn-1 routing (first-writer-wins)
    assert val(p1) == 11 and val(p1 + 1) == 22  # action1 trailing token backfilled by turn-2 prefill
    assert re[-1] is None and all(r is not None for r in re[:-1])  # only the final trailing token unrouted


def test_compaction_starts_a_fresh_segment():
    # An agent that rewrites/shortens history (compaction) no longer prefix-extends the running
    # segment, so a fresh token-exact segment starts — NOT a token-drift split. Both segments are
    # returned and carry the terminal reward (one rollout_id -> deduped to one reward downstream).
    a1, a2, a3 = "A1", "A2", "A3"
    engine = _DriftyEngine(
        [_dact(_ids(a1), [-0.1] * len(a1)), _dact(_ids(a2), [-0.2] * len(a2)), _dact(_ids(a3), [-0.3] * len(a3))]
    )
    state = ChatServerState(engine, _DriftyProc(), "policy", 10000, _sampling())
    state.open("sid", "P", "lab", None)
    session = state.sessions["sid"]

    msgs = [{"role": "user", "content": "Q0"}]
    r1, _ = _drive(state, session, msgs)
    msgs = msgs + [{"role": "assistant", "content": r1}, {"role": "user", "content": "OBS1"}]
    _drive(state, session, msgs)  # normal continuation -> same segment
    assert len(session.trajectories) == 1 and len(session.trajectories[0].action_ranges) == 2

    # Compaction: the agent replaces the whole history with a summary — the prefix no longer matches.
    compacted = [{"role": "user", "content": "SUMMARY"}]
    r3, _ = _drive(state, session, compacted)
    assert len(session.trajectories) == 2  # a genuine rewrite -> new segment, not a drift split
    proc = _DriftyProc()
    expected2 = _ids(proc.apply_chat_template(compacted, add_generation_prompt=True)) + _ids(r3)
    assert session.trajectories[1].observation_tokens == expected2  # segment 2 token-exact from compacted
    assert [len(t.action_ranges) for t in session.trajectories] == [2, 1]

    out = stitch_session(state, "sid", Result(reward=1.0, score=0.5))
    assert len(out) == 2 and all(t.reward == 1.0 and t.scores == 0.5 for t in out)


def test_run_turn_replays_retried_turn_idempotently(monkeypatch):
    _patch_prompts(monkeypatch, [[1, 2]])
    state, tp = _state([_act([90], [-0.1])])
    state.open("sid", "P", "l", None)
    session = state.sessions["sid"]
    r1 = asyncio.run(_run_turn(state, session, _MSG))
    r2 = asyncio.run(_run_turn(state, session, {"messages": [{"role": "user", "content": "P"}]}))
    # cached, no 2nd generate: one trajectory with a single action range
    assert r1 == r2 and len(session.trajectories) == 1
    assert len(session.trajectories[0].action_ranges) == 1 and len(tp.calls) == 1


class _FlakyTransport(_FakeTransport):
    """Raises on the listed 0-indexed generate calls (a transient engine 500 the stock SDK retries)
    WITHOUT consuming an action, so a retry hits the next call."""

    def __init__(self, actions, fail_calls):
        super().__init__(actions)
        self.fail_calls = set(fail_calls)
        self._n = 0

    async def generate(self, prompt_token_ids, sampling_params, multi_modal_data=None, session_id=None):
        c, self._n = self._n, self._n + 1
        if c in self.fail_calls:
            raise RuntimeError("transient engine 500")
        return await super().generate(prompt_token_ids, sampling_params, multi_modal_data, session_id)


def test_turn1_generate_failure_then_retry_is_clean(monkeypatch):
    # A mid-turn generate failure must leave the session untouched so the stock client's retry re-runs
    # cleanly — no half-built segment (which on turn 1 would crash the extends check on len(None)).
    _patch_prompts(monkeypatch, [[1, 2, 3], [1, 2, 3]])  # turn 1 tokenizes on the failed try AND the retry
    tp = _FlakyTransport([_act([90], [-0.1])], fail_calls={0})
    state = ChatServerState(tp, _proc(), "policy", 1000, _sampling())
    state.open("sid", "P", "lab", None)
    session = state.sessions["sid"]
    with pytest.raises(RuntimeError):
        asyncio.run(_run_turn(state, session, _MSG))
    assert session.trajectories == []  # failed generate left NO half-built segment
    action, _ = asyncio.run(_run_turn(state, session, _MSG))  # retry: must not raise TypeError
    assert action == "ACT" and len(session.trajectories) == 1
    assert session.trajectories[0].observation_tokens == [1, 2, 3, 90]


def test_continuation_generate_failure_then_retry_no_double_append(monkeypatch):
    # A continuation whose generate fails must not leave its delta half-appended; the retry appends it
    # exactly once (else the trained context would carry the tool feedback twice).
    _patch_prompts(monkeypatch, [[1, 2, 3]])
    monkeypatch.setattr(cs, "_tokenize_feedback", lambda proc, text, imgs, traj, ml: [50, 51])
    tp = _FlakyTransport([_act([90], [-0.1]), _act([91], [-0.2])], fail_calls={1})  # turn-2 first generate fails
    state = ChatServerState(tp, _proc(), "policy", 1000, _sampling())
    state.open("sid", "P", "lab", None)
    session = state.sessions["sid"]
    asyncio.run(_run_turn(state, session, _MSG))  # turn 1 ok
    traj = session.trajectories[0]
    msgs2 = {
        "messages": [
            {"role": "user", "content": "P"},
            {"role": "assistant", "content": "ACT"},
            {"role": "user", "content": "obs"},
        ]
    }
    with pytest.raises(RuntimeError):
        asyncio.run(_run_turn(state, session, msgs2))
    assert traj.observation_tokens == [1, 2, 3, 90]  # delta NOT appended on the failed attempt
    asyncio.run(_run_turn(state, session, msgs2))  # retry
    assert traj.observation_tokens == [1, 2, 3, 90, 50, 51, 91]  # delta + action appended exactly once
    assert len(session.trajectories) == 1 and traj.action_ranges == [(3, 4), (6, 7)]


def test_run_turn_ends_truncated_on_context_overflow(monkeypatch):
    _patch_prompts(monkeypatch, [list(range(5000))])
    state, tp = _state([_act([90], [-0.1])], max_length=100)
    state.open("sid", "P", "l", None)
    action, finish = asyncio.run(_run_turn(state, state.sessions["sid"], _MSG))
    assert (action, finish) == ("", "length")
    assert state.sessions["sid"].trajectories == [] and tp.calls == []


def test_later_context_overflow_survives_stitch_with_episode_truncation(monkeypatch):
    _patch_prompts(monkeypatch, [[1, 2], list(range(10))])
    state, tp = _state([_act([90], [-0.1])], max_length=10)
    state.open("sid", "P", "l", None)
    session = state.sessions["sid"]

    asyncio.run(_run_turn(state, session, _MSG))
    action, finish = asyncio.run(_run_turn(state, session, {"messages": [{"role": "user", "content": "full"}]}))
    out = stitch_session(
        state,
        "sid",
        Result(reward=0.0, truncated=True, info={"truncated": True}),
    )

    assert (action, finish) == ("", "length")
    assert len(tp.calls) == 1 and len(out) == 1
    assert out[0].truncated is True
    assert out[0].extra_logs["generation_truncated"] is True
    assert out[0].extra_logs["truncated"] is True


def test_run_turn_marks_truncated_on_length_finish(monkeypatch):
    _patch_prompts(monkeypatch, [[1]])
    state, _ = _state([_act([90, 91], [-0.1, -0.2], finish="length")])
    state.open("sid", "P", "l", None)
    _, finish = asyncio.run(_run_turn(state, state.sessions["sid"], _MSG))
    assert finish == "length" and state.sessions["sid"].trajectories[0].truncated is True


def test_run_turn_clamps_max_tokens_to_remaining(monkeypatch):
    _patch_prompts(monkeypatch, [[1, 2, 3, 4]])
    state, tp = _state([_act([90], [-0.1])], max_length=10)
    state.default_sampling = SimpleNamespace(max_tokens=None, temperature=1.0, top_p=1.0, logprobs=1, min_tokens=0)
    state.open("sid", "P", "l", None)
    asyncio.run(_run_turn(state, state.sessions["sid"], _MSG))
    assert tp.calls[0][2] == 6  # 10 - 4 prompt tokens


def test_run_turn_raises_on_logprobs_count_mismatch(monkeypatch):
    _patch_prompts(monkeypatch, [[1, 2]])
    state, _ = _state([_act([90, 91], [-0.1])])  # 2 action tokens, 1 logprob
    state.open("sid", "P", "l", None)
    with pytest.raises(RuntimeError, match="logprob"):
        asyncio.run(_run_turn(state, state.sessions["sid"], _MSG))


def test_run_turn_vlm_carries_pixel_values(monkeypatch):
    _patch_prompts(monkeypatch, [[999, 999, 7]], mm={"pixel_values": np.ones((1, 3, 4, 4))}, pil=["PIL"])
    monkeypatch.setattr(cs, "estimate_vllm_input_expansion_delta", lambda *a, **k: 5)
    state, tp = _state([_act([90], [-0.1])])
    state.open("sid", "P", "l", None)
    msg = {"messages": [{"role": "user", "content": [{"type": "image_url", "image_url": {"url": "u"}}]}]}
    asyncio.run(_run_turn(state, state.sessions["sid"], msg))
    traj = state.sessions["sid"].trajectories[0]
    assert traj.observation_tokens[:3] == [999, 999, 7]
    assert traj.mm_train_inputs["pixel_values"].shape[0] == 1 and traj.image_budget == 5
    assert tp.calls[0][1] == {"image": ["PIL"]}  # images forwarded to generate as multi_modal_data


def test_multiturn_vlm_carries_image_and_absorbs_a_new_one(monkeypatch):
    # The two multi-turn VLM cases geo3k (image only in turn 1) does NOT exercise: (1) turn 1's image
    # must PERSIST across a later text turn — pixel_values/budget kept, generation still gets mm_data;
    # (2) a turn that adds a NEW image must accumulate it into the same trajectory (the delta path).
    monkeypatch.setattr(cs, "load_images", lambda url: ["PIL1"])
    monkeypatch.setattr(cs, "estimate_vllm_input_expansion_delta", lambda *a, **k: 5)
    monkeypatch.setattr(
        cs,
        "_tokenize_observation",
        lambda proc, text, imgs: ([1, 2, 3], {"pixel_values": np.ones((1, 3, 4, 4))}, list(imgs)),
    )

    def fake_feedback(proc, text, new_images, traj, max_len):
        if new_images:  # mirror the real _tokenize_feedback: accumulate the new image in place
            traj.pil_images.extend(new_images)
            traj.mm_train_inputs = {"pixel_values": np.ones((len(traj.pil_images), 3, 4, 4))}
            traj.image_budget += 5
            return [60, 61]
        return [50, 51]  # text-only delta

    monkeypatch.setattr(cs, "_tokenize_feedback", fake_feedback)
    state, tp = _state([_act([90], [-0.1]), _act([91], [-0.2]), _act([92], [-0.3])])
    state.open("sid", "P", "lab", None)
    session = state.sessions["sid"]

    img = [{"role": "user", "content": [{"type": "image_url", "image_url": {"url": "u"}}]}]
    _drive(state, session, img)  # turn 1: the image
    traj = session.trajectories[0]
    assert traj.pil_images == ["PIL1"] and tp.calls[0][1] == {"image": ["PIL1"]}

    # turn 2: a TEXT tool response -> the image must NOT be dropped and must still reach generation
    msgs = img + [{"role": "assistant", "content": "ACT"}, {"role": "user", "content": "obs"}]
    _drive(state, session, msgs)
    assert len(session.trajectories) == 1 and traj.pil_images == ["PIL1"]  # same segment, image kept
    assert tp.calls[1][1] == {"image": ["PIL1"]}

    # turn 3: a NEW image mid-conversation -> accumulated into the one trajectory (both forwarded)
    monkeypatch.setattr(cs, "load_images", lambda url: ["PIL2"])
    msgs = msgs + [
        {"role": "assistant", "content": "ACT"},
        {"role": "user", "content": [{"type": "image_url", "image_url": {"url": "u2"}}]},
    ]
    _drive(state, session, msgs)
    assert traj.pil_images == ["PIL1", "PIL2"] and traj.mm_train_inputs["pixel_values"].shape[0] == 2
    assert traj.image_budget == 10 and tp.calls[2][1] == {"image": ["PIL1", "PIL2"]}
    # token-exact across all 3 turns (image prompt + action + text delta + action + image delta + action)
    assert traj.observation_tokens == [1, 2, 3, 90, 50, 51, 91, 60, 61, 92]
    assert traj.action_ranges == [(3, 4), (6, 7), (9, 10)]


def test_run_turn_absorbs_unified_routing_by_position(monkeypatch):
    _patch_prompts(monkeypatch, [[1, 2, 3]])
    routed = [[10], [11], [12], [20], [21]]  # unified [tokens,layer,topk]: 3 prompt + 2 action rows
    state, _ = _state([_act([90, 91], [-0.1, -0.2], routed=routed)])
    state.open("sid", "P", "l", None)
    asyncio.run(_run_turn(state, state.sessions["sid"], _MSG))
    assert [r[0] for r in state.sessions["sid"].trajectories[0].routed_experts] == [10, 11, 12, 20, 21]


# ---------------------------------------------------------------------------
# _content_to_text_and_images — OpenAI content -> (flat text w/ <image>, PIL list).
# ---------------------------------------------------------------------------
def test_content_flatten_string_passthrough():
    assert _content_to_text_and_images("hello") == ("hello", [])


def test_content_flatten_collects_images(monkeypatch):
    monkeypatch.setattr(cs, "load_images", lambda url: ["PIL"])
    text, pil = _content_to_text_and_images(
        [{"type": "text", "text": "look:"}, {"type": "image_url", "image_url": {"url": "u"}}]
    )
    assert text == "look:<image>" and pil == ["PIL"]


# ---------------------------------------------------------------------------
# stitch_session: every token-exact segment gets the terminal reward (usually one).
# ---------------------------------------------------------------------------
def test_stitch_drops_stepless_session():
    # Opened but never generated (e.g. the first prompt alone exceeded max_length) -> no trajectories
    # rather than an error; run_group then drops the rollout.
    state, _ = _state([])
    state.open("sid", "p", "l", None)
    assert stitch_session(state, "sid", Result(reward=0.0)) == []


def test_stitch_raises_on_unknown_session():
    state, _ = _state([])
    with pytest.raises(RuntimeError, match="Unknown session"):
        stitch_session(state, "missing", Result(reward=0.0))


def test_stitch_returns_one_trajectory_stamped_with_reward():
    # A multi-turn episode is ONE trajectory (an action range per turn), stamped with the terminal
    # reward/score — not one sample per turn.
    engine = _DriftyEngine([_dact(_ids("A1"), [-0.1, -0.1]), _dact(_ids("A2"), [-0.2, -0.2])])
    state = ChatServerState(engine, _DriftyProc(), "policy", 10000, _sampling())
    state.open("sid", "P", "l", None)
    session = state.sessions["sid"]
    msgs = [{"role": "user", "content": "Q0"}]
    act1, _ = _drive(state, session, msgs)
    _drive(state, session, msgs + [{"role": "assistant", "content": act1}, {"role": "user", "content": "OBS1"}])
    out = stitch_session(state, "sid", Result(reward=1.0, score=0.5))
    assert len(out) == 1
    assert len(out[0].action_ranges) == 2  # both turns on the one trajectory
    assert out[0].reward == 1.0 and out[0].scores == 0.5


def test_stitch_propagates_environment_truncation_to_trajectory():
    engine = _DriftyEngine([_dact(_ids("A1"), [-0.1, -0.1]), _dact(_ids("A2"), [-0.2, -0.2])])
    state = ChatServerState(engine, _DriftyProc(), "policy", 10000, _sampling())
    state.open("sid", "P", "l", None)
    session = state.sessions["sid"]
    msgs = [{"role": "user", "content": "Q0"}]
    act1, _ = _drive(state, session, msgs)
    _drive(state, session, msgs + [{"role": "assistant", "content": act1}, {"role": "user", "content": "OBS1"}])

    out = stitch_session(state, "sid", Result(reward=0.0, truncated=True))

    assert len(out) == 1
    assert out[0].truncated is True
    assert out[0].extra_logs["generation_truncated"] is False


# ---------------------------------------------------------------------------
# Wire codecs — Anthropic decode + reply encoders (transport-independent).
# ---------------------------------------------------------------------------
def test_chat_completion_body_normalizes_finish_reason():
    for raw in ("abort", "error", "repetition", None):
        assert _chat_completion_body("policy", "x", raw)["choices"][0]["finish_reason"] == "stop"
    for raw in ("stop", "length", "tool_calls"):
        assert _chat_completion_body("policy", "x", raw)["choices"][0]["finish_reason"] == raw


def test_decode_anthropic_normalizes_to_openai_shape():
    body = {
        "system": "sys",
        "max_tokens": 64,
        "messages": [
            {"role": "user", "content": "hi"},
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": "look:"},
                    {"type": "image", "source": {"type": "base64", "media_type": "image/png", "data": "AAAA"}},
                ],
            },
        ],
    }
    out = _decode_anthropic(body)
    assert all(m["role"] != "system" for m in out["messages"]) and len(out["messages"]) == 2
    blocks = out["messages"][1]["content"]
    assert blocks[1] == {"type": "image_url", "image_url": {"url": "data:image/png;base64,AAAA"}}


def test_decode_anthropic_unwraps_tool_result():
    body = {
        "max_tokens": 64,
        "messages": [{"role": "user", "content": [{"type": "tool_result", "tool_use_id": "t", "content": "4"}]}],
    }
    out = _decode_anthropic(body)
    assert out["messages"][0]["content"] == [{"type": "text", "text": "4"}]


def test_anthropic_message_body_maps_stop_reason():
    for raw, want in (("stop", "end_turn"), ("length", "max_tokens"), ("tool_calls", "tool_use")):
        assert _anthropic_message_body("policy", "x", raw)["stop_reason"] == want


def test_response_bodies_parse_with_real_sdk_models():
    chat_types = pytest.importorskip("openai.types.chat")
    anthropic_types = pytest.importorskip("anthropic.types")
    completion = chat_types.ChatCompletion.model_validate(_chat_completion_body("policy", "hi", "abort"))
    assert completion.choices[0].message.content == "hi"
    message = anthropic_types.Message.model_validate(_anthropic_message_body("policy", "hi", "length"))
    assert message.content[0].text == "hi" and message.stop_reason == "max_tokens"
